---

- name: Update mongod.conf with replicaset
  template: 
    src: mongodb.replicaset.conf.j2
    dest: /etc/mongod.conf
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart mongod"
